### ISSUE TITLE
Tricky Code

### ISSUE THREAD

**Issue by Z4nR** [Z4nR/13.LetterVault#1]
I found a tricky code about Notification Worker. So, the code must be trigger when I clicked save button. But in this condition the code more tricky. 

[The code in detail. But this true position is at add activity in save button. ](https://github.com/Z4nR/13.LetterVault/blob/master/app/src/main/java/com/google/developers/lettervault/ui/detail/LetterDetailActivity.kt)

**Comment by Z4nR** [comment]
thanks, taufan. I have tried your code but it doesn't work at all, still not push notification on at my emu.

**Comment by taufan-mft** [comment]
check again
